---
- hosts: deploy
  remote_user: root
  gather_facts: true
  connection: local
  pre_tasks:
  - name: Inclure les variables de la VM
    include_vars:
      file: "{{ playbook_dir }}/host_vars/{{ inventory_hostname}}/main.yml"

  tasks:
  - name: Inclure les roles
    include_role:
      name: role-deploy-ssh-key-000
      allow_duplicates: false
